stackoverflow:
  outputs:
    my_output:
      type: bigquery
      method: oauth
      project: lydia-sandbox-390714
      dataset: stackoverflow
      location: US
      threads: 1
      timeout_seconds: 300
      priority: interactive
      name: stackoverflow
      sandbox: false
  target: my_output
